/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import controller.CompraController;
import controller.PagamentoController;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import model.Cartao;
import model.Compra;
import model.Pagamento;

/**
 *
 * @author jose.yamaoki_unesp
 */
public class CardCartao extends javax.swing.JPanel {
    private boolean selecionado = false;
    /**
     * Creates new form CardLeilao
     * @param anuncio
     */
    public CardCartao(Cartao cartao, Compra compra) {
        initComponents();
        
        nomeMetodoField.setText(cartao.getNomeMeioPagamento());
        nomeTitularField.setText(cartao.getNomeTitular());
        numeroField.setText(cartao.getNumero());
        cvvField.setText(cartao.getCvv());
        setBackground(Color.LIGHT_GRAY); // cor padrão
        setBorder(BorderFactory.createLineBorder(Color.GRAY));

        addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                selecionado = true;
                atualizarEstilo();
                int resposta = javax.swing.JOptionPane.showConfirmDialog(CardCartao.this,
                    "Deseja realmente pagar com este cartão?",
                    "Confirmar pagamento",
                    javax.swing.JOptionPane.YES_NO_OPTION
                );

                if (resposta == javax.swing.JOptionPane.YES_OPTION) {
                    try {
                        CompraController.editarStatusCompra(compra);
                        Pagamento p = new Pagamento(null, compra.getVendedor(), compra, cartao, LocalDateTime.now());
                        PagamentoController.inserirPagamento(p);
                    } catch (IOException ex) {
                        Logger.getLogger(CardCartao.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    javax.swing.JOptionPane.showMessageDialog(CardCartao.this, "Pagamento efetuado com sucesso.");
                    java.awt.Component c = CardCartao.this;
                    while (c != null && !(c instanceof javax.swing.JDialog)) {
                        c = c.getParent();
                    }
                    if (c instanceof javax.swing.JDialog dialog) {
                        dialog.dispose();
                    }
                }
                selecionado = false;
                atualizarEstilo();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numeroLabel = new javax.swing.JLabel();
        nomeTitularLabel = new javax.swing.JLabel();
        nomeMetodoLabel = new javax.swing.JLabel();
        nomeTitularField = new javax.swing.JTextField();
        nomeMetodoField = new javax.swing.JTextField();
        numeroField = new javax.swing.JTextField();
        cvvLabel = new javax.swing.JLabel();
        cvvField = new javax.swing.JTextField();

        numeroLabel.setText("Número:");

        nomeTitularLabel.setText("Nome Titular:");

        nomeMetodoLabel.setText("Nome Método:");

        nomeTitularField.setEditable(false);
        nomeTitularField.setText("jTextField1");
        nomeTitularField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTitularFieldActionPerformed(evt);
            }
        });

        nomeMetodoField.setEditable(false);
        nomeMetodoField.setText("jTextField2");
        nomeMetodoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeMetodoFieldActionPerformed(evt);
            }
        });

        numeroField.setEditable(false);
        numeroField.setText("jTextField1");
        numeroField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroFieldActionPerformed(evt);
            }
        });

        cvvLabel.setText("CVV:");

        cvvField.setEditable(false);
        cvvField.setText("jTextField1");
        cvvField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvvFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeMetodoLabel)
                            .addComponent(numeroLabel)
                            .addComponent(nomeTitularLabel))
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeTitularField, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                            .addComponent(nomeMetodoField)
                            .addComponent(numeroField, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cvvLabel)
                        .addGap(143, 143, 143)
                        .addComponent(cvvField, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeMetodoLabel)
                    .addComponent(nomeMetodoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeTitularLabel)
                    .addComponent(nomeTitularField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroLabel)
                    .addComponent(numeroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cvvLabel)
                    .addComponent(cvvField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nomeMetodoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeMetodoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeMetodoFieldActionPerformed

    private void nomeTitularFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTitularFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTitularFieldActionPerformed

    private void numeroFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroFieldActionPerformed

    private void cvvFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvvFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvvFieldActionPerformed

    private void atualizarEstilo() {
        if (selecionado) {
            setBackground(Color.CYAN);
            setBorder(BorderFactory.createLineBorder(Color.BLUE, 2));
        } else {
            setBackground(Color.LIGHT_GRAY);
            setBorder(BorderFactory.createLineBorder(Color.GRAY));
        }
        repaint();
    }

    public boolean isSelecionado() {
        return selecionado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cvvField;
    private javax.swing.JLabel cvvLabel;
    private javax.swing.JTextField nomeMetodoField;
    private javax.swing.JLabel nomeMetodoLabel;
    private javax.swing.JTextField nomeTitularField;
    private javax.swing.JLabel nomeTitularLabel;
    private javax.swing.JTextField numeroField;
    private javax.swing.JLabel numeroLabel;
    // End of variables declaration//GEN-END:variables
}
