/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import model.Notificacao;

/**
 *
 * @author jose.yamaoki_unesp
 */
public class CardNotificacao extends javax.swing.JPanel {
    private boolean selecionado = false;
    /**
     * Creates new form CardLeilao
     * @param anuncio
     */
    public CardNotificacao(Notificacao notificacao) {
        initComponents();
        
        mensagemField.setText(notificacao.getMensagem());
        setBackground(Color.LIGHT_GRAY); // cor padrão
        setBorder(BorderFactory.createLineBorder(Color.GRAY));

        addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                selecionado = true;
                atualizarEstilo();
                notificacao.visualizar();
                javax.swing.JOptionPane.showMessageDialog(CardNotificacao.this, "Notificacao visualizada com sucesso.");
                selecionado = false;
                atualizarEstilo();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mensagemLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mensagemField = new javax.swing.JTextArea();

        mensagemLabel.setText("Mensagem:");

        mensagemField.setEditable(false);
        mensagemField.setColumns(20);
        mensagemField.setRows(5);
        jScrollPane1.setViewportView(mensagemField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(mensagemLabel)
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mensagemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarEstilo() {
        if (selecionado) {
            setBackground(Color.CYAN);
            setBorder(BorderFactory.createLineBorder(Color.BLUE, 2));
        } else {
            setBackground(Color.LIGHT_GRAY);
            setBorder(BorderFactory.createLineBorder(Color.GRAY));
        }
        repaint();
    }

    public boolean isSelecionado() {
        return selecionado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea mensagemField;
    private javax.swing.JLabel mensagemLabel;
    // End of variables declaration//GEN-END:variables
}
