/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.BorderFactory;
import model.Compra;

/**
 *
 * @author jose.yamaoki_unesp
 */
public class CardCompra extends javax.swing.JPanel {
    private boolean selecionado = false;
    
    /**
     * Creates new form CardLeilao
     * @param anuncio
     */
    public CardCompra(Compra compra) {
        initComponents();
        vendedorField.setText(compra.getVendedor().getNome());
        valorField.setText(Double.toString(compra.getValor()));
        
        LocalDateTime time = compra.getData();
        String pattern = "dd-MM-yyyy HH:mm:ss";
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern(pattern);

        String formattedDateTime = time.format(formatter);
        
        dataField.setText(formattedDateTime);
        
        anuncioField.setText(compra.getAnuncio().getNome());
        
        setBackground(Color.LIGHT_GRAY); // cor padrão
        setBorder(BorderFactory.createLineBorder(Color.GRAY));

        addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                selecionado = true;
                atualizarEstilo();
                DetalheCompra detalheCompra;
                detalheCompra = new DetalheCompra(null, true, compra);
                detalheCompra.setLocationRelativeTo(CardCompra.this);
                detalheCompra.setVisible(true);
                selecionado = false;
                atualizarEstilo();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataLabel = new javax.swing.JLabel();
        valorLabel = new javax.swing.JLabel();
        vendedorLabel = new javax.swing.JLabel();
        valorField = new javax.swing.JTextField();
        vendedorField = new javax.swing.JTextField();
        dataField = new javax.swing.JTextField();
        anuncioLabel = new javax.swing.JLabel();
        anuncioField = new javax.swing.JTextField();

        dataLabel.setText("Data:");

        valorLabel.setText("Valor:");

        vendedorLabel.setText("Vendedor:");

        valorField.setEditable(false);
        valorField.setText("jTextField1");
        valorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorFieldActionPerformed(evt);
            }
        });

        vendedorField.setEditable(false);
        vendedorField.setText("jTextField2");
        vendedorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendedorFieldActionPerformed(evt);
            }
        });

        dataField.setEditable(false);
        dataField.setText("jTextField1");
        dataField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataFieldActionPerformed(evt);
            }
        });

        anuncioLabel.setText("Anúncio:");

        anuncioField.setEditable(false);
        anuncioField.setText("jTextField1");
        anuncioField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anuncioFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vendedorLabel)
                    .addComponent(dataLabel)
                    .addComponent(valorLabel)
                    .addComponent(anuncioLabel))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valorField, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                    .addComponent(vendedorField)
                    .addComponent(dataField)
                    .addComponent(anuncioField))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vendedorLabel)
                    .addComponent(vendedorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorLabel)
                    .addComponent(valorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataLabel)
                    .addComponent(dataField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anuncioLabel)
                    .addComponent(anuncioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void vendedorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendedorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vendedorFieldActionPerformed

    private void valorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorFieldActionPerformed

    private void dataFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataFieldActionPerformed

    private void anuncioFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anuncioFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anuncioFieldActionPerformed

    private void atualizarEstilo() {
        if (selecionado) {
            setBackground(Color.CYAN);
            setBorder(BorderFactory.createLineBorder(Color.BLUE, 2));
        } else {
            setBackground(Color.LIGHT_GRAY);
            setBorder(BorderFactory.createLineBorder(Color.GRAY));
        }
        repaint();
    }

    public boolean isSelecionado() {
        return selecionado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anuncioField;
    private javax.swing.JLabel anuncioLabel;
    private javax.swing.JTextField dataField;
    private javax.swing.JLabel dataLabel;
    private javax.swing.JTextField valorField;
    private javax.swing.JLabel valorLabel;
    private javax.swing.JTextField vendedorField;
    private javax.swing.JLabel vendedorLabel;
    // End of variables declaration//GEN-END:variables
}
