/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui;

import controller.CartaoController;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Cartao;

/**
 *
 * @author vitor
 */
public class EditarCartao extends javax.swing.JDialog {
    private Cartao cartao;
    private int opt = -1;

    /**
     * Creates new form EditarCartao
     */
    public EditarCartao(java.awt.Frame parent, boolean modal, Cartao cartao) {
        super(parent, modal);
        initComponents();
        dadoField.setVisible(false);
        dadoLabel.setVisible(false);
        confirmarButton.setVisible(false);
        this.cartao = cartao;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dadoField = new javax.swing.JTextField();
        dadoLabel = new javax.swing.JLabel();
        confirmarButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        editarMenu = new javax.swing.JMenu();
        nomeMetodoItem = new javax.swing.JMenuItem();
        nomeTitularItem = new javax.swing.JMenuItem();
        numeroItem = new javax.swing.JMenuItem();
        cvvItem = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dadoLabel.setText("Digite o novo dado:");

        confirmarButton.setText("Confirmar");
        confirmarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarButtonActionPerformed(evt);
            }
        });

        editarMenu.setText("Editar");

        nomeMetodoItem.setText("Nome Método");
        nomeMetodoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeMetodoItemActionPerformed(evt);
            }
        });
        editarMenu.add(nomeMetodoItem);

        nomeTitularItem.setText("Nome Titular");
        nomeTitularItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTitularItemActionPerformed(evt);
            }
        });
        editarMenu.add(nomeTitularItem);

        numeroItem.setText("Número");
        numeroItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroItemActionPerformed(evt);
            }
        });
        editarMenu.add(numeroItem);

        cvvItem.setText("CVV");
        cvvItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvvItemActionPerformed(evt);
            }
        });
        editarMenu.add(cvvItem);

        jMenuBar1.add(editarMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dadoLabel)
                        .addGap(42, 42, 42)
                        .addComponent(dadoField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dadoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dadoField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(confirmarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeTitularItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTitularItemActionPerformed
        // TODO add your handling code here:
        dadoField.setVisible(true);
        dadoLabel.setVisible(true);
        confirmarButton.setVisible(true);
        opt = 0;
    }//GEN-LAST:event_nomeTitularItemActionPerformed

    private void nomeMetodoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeMetodoItemActionPerformed
        // TODO add your handling code here:
        dadoField.setVisible(true);
        dadoLabel.setVisible(true);
        confirmarButton.setVisible(true);
        opt = 1;
    }//GEN-LAST:event_nomeMetodoItemActionPerformed

    private void numeroItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroItemActionPerformed
        // TODO add your handling code here:
        dadoField.setVisible(true);
        dadoLabel.setVisible(true);
        confirmarButton.setVisible(true);
        opt = 2;
    }//GEN-LAST:event_numeroItemActionPerformed

    private void cvvItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvvItemActionPerformed
        // TODO add your handling code here:
        dadoField.setVisible(true);
        dadoLabel.setVisible(true);
        confirmarButton.setVisible(true);
        opt = 3;
    }//GEN-LAST:event_cvvItemActionPerformed

    private void confirmarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarButtonActionPerformed
        // TODO add your handling code here:
        switch(opt){
            case 0:
                if(!CartaoController.validarNomeTitular(dadoField.getText())){
                    javax.swing.JOptionPane.showMessageDialog(this, "Nome inválido.");
                }else{
            try {
                CartaoController.setNomeTitularCartao(dadoField.getText(), cartao);
                cartao.getComprador().getCartoes().remove(cartao);
            } catch (IOException ex) {
                Logger.getLogger(EditarCartao.class.getName()).log(Level.SEVERE, null, ex);
            }
                    javax.swing.JOptionPane.showMessageDialog(this, "Nome do titular modificado com sucesso.");
                }
                break;
            case 1:
                if(!CartaoController.validarNomeMetodo(dadoField.getText())){
                    javax.swing.JOptionPane.showMessageDialog(this, "Nome inválido.");
                }else{
            try {
                CartaoController.setNomeMetodoCartao(dadoField.getText(), cartao);
                cartao.getComprador().getCartoes().remove(cartao);
            } catch (IOException ex) {
                Logger.getLogger(EditarCartao.class.getName()).log(Level.SEVERE, null, ex);
            }
                    javax.swing.JOptionPane.showMessageDialog(this, "Nome do método modificado com sucesso.");
                }
                break;
            case 2:
                if(!CartaoController.validarNumero(dadoField.getText())){
                    javax.swing.JOptionPane.showMessageDialog(this, "Número inválido.");
                }else{
            try {
                CartaoController.setNumeroCartao(dadoField.getText(), cartao);
                cartao.getComprador().getCartoes().remove(cartao);
            } catch (IOException ex) {
                Logger.getLogger(EditarCartao.class.getName()).log(Level.SEVERE, null, ex);
            }
                    javax.swing.JOptionPane.showMessageDialog(this, "Número modificado com sucesso.");
                }
                break;
            case 3:
                if(!CartaoController.validarCVV(dadoField.getText())){
                    javax.swing.JOptionPane.showMessageDialog(this, "CVV inválido.");
                }else{
            try {
                CartaoController.setCVVCartao(dadoField.getText(), cartao);
                cartao.getComprador().getCartoes().remove(cartao);
            } catch (IOException ex) {
                Logger.getLogger(EditarCartao.class.getName()).log(Level.SEVERE, null, ex);
            }
                    javax.swing.JOptionPane.showMessageDialog(this, "CVV modificado com sucesso.");
                }
                break;
            default:
                break;
        }
        
        this.dispose();
    }//GEN-LAST:event_confirmarButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmarButton;
    private javax.swing.JMenuItem cvvItem;
    private javax.swing.JTextField dadoField;
    private javax.swing.JLabel dadoLabel;
    private javax.swing.JMenu editarMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem nomeMetodoItem;
    private javax.swing.JMenuItem nomeTitularItem;
    private javax.swing.JMenuItem numeroItem;
    // End of variables declaration//GEN-END:variables
}
