/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui;

import controller.CompradorController;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import model.Cartao;
import model.Compra;
import model.Sistema;

/**
 *
 * @author jose.yamaoki_unesp
 */
public class ListarCartoes extends javax.swing.JDialog {
    private Compra compra;

    /**
     * Creates new form ListarAnuncios
     */
    public ListarCartoes(java.awt.Frame parent, boolean modal, Compra compra) {
        super(parent, modal);
        initComponents();
        this.compra = compra;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 764, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        // Container para os cards
        JPanel container = new JPanel();
        container.setLayout(new BoxLayout(container, BoxLayout.Y_AXIS));
        
        CompradorController compradorController = new CompradorController();
        
        List<Cartao> cartoes = compradorController.getTodosCartoesComprador(Sistema.getInstance().getUsuarioLogado().getId());
        for (int i = 0; i < cartoes.size(); i++) {
            CardCartao card;
            card = new CardCartao(cartoes.get(i), compra);
            container.add(card);
        }

        // Adiciona o container ao JDialog
        this.setLayout(new BorderLayout());
        this.add(new JScrollPane(container), BorderLayout.CENTER);

        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_formWindowOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
