/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Sistema;

/**
 *
 * @author vitor
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        cadastroMenu = new javax.swing.JMenu();
        cadastroVendedor = new javax.swing.JMenuItem();
        cadastroComprador = new javax.swing.JMenuItem();
        loginMenu = new javax.swing.JMenu();
        usuarioLogin = new javax.swing.JMenuItem();
        anunciosMenu = new javax.swing.JMenu();
        anuncios = new javax.swing.JMenuItem();
        anunciosAtivos = new javax.swing.JMenuItem();
        anunciosEncerrados = new javax.swing.JMenuItem();
        buscarNome = new javax.swing.JMenuItem();
        anunciosVendedor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeLabel.setText("Não Logado");

        cadastroMenu.setText("Cadastro");
        cadastroMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroMenuActionPerformed(evt);
            }
        });

        cadastroVendedor.setText("Cadastro de Vendedor");
        cadastroVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroVendedorActionPerformed(evt);
            }
        });
        cadastroMenu.add(cadastroVendedor);

        cadastroComprador.setText("Cadastro de Comprador");
        cadastroComprador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroCompradorActionPerformed(evt);
            }
        });
        cadastroMenu.add(cadastroComprador);

        jMenuBar1.add(cadastroMenu);

        loginMenu.setText("Login");

        usuarioLogin.setText("Login de Usuário");
        usuarioLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioLoginActionPerformed(evt);
            }
        });
        loginMenu.add(usuarioLogin);

        jMenuBar1.add(loginMenu);

        anunciosMenu.setText("Anúncios");

        anuncios.setText("Todos Anúncios");
        anuncios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anunciosActionPerformed(evt);
            }
        });
        anunciosMenu.add(anuncios);

        anunciosAtivos.setText("Anúncios Ativos");
        anunciosAtivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anunciosAtivosActionPerformed(evt);
            }
        });
        anunciosMenu.add(anunciosAtivos);

        anunciosEncerrados.setText("Anúncios Encerrados");
        anunciosEncerrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anunciosEncerradosActionPerformed(evt);
            }
        });
        anunciosMenu.add(anunciosEncerrados);

        buscarNome.setText("Buscar por Nome");
        buscarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarNomeActionPerformed(evt);
            }
        });
        anunciosMenu.add(buscarNome);

        anunciosVendedor.setText("Buscar por Vendedor");
        anunciosVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anunciosVendedorActionPerformed(evt);
            }
        });
        anunciosMenu.add(anunciosVendedor);

        jMenuBar1.add(anunciosMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(224, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroMenuActionPerformed

    }//GEN-LAST:event_cadastroMenuActionPerformed

    private void cadastroVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroVendedorActionPerformed
        // TODO add your handling code here:
        CadastroVendedorUI cadUI = new CadastroVendedorUI(this, true);
        cadUI.setLocationRelativeTo(this);
        cadUI.setVisible(true);
    }//GEN-LAST:event_cadastroVendedorActionPerformed

    private void cadastroCompradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroCompradorActionPerformed
        // TODO add your handling code here:
        CadastroCompradorUI cadUI = new CadastroCompradorUI(this, true);
        cadUI.setLocationRelativeTo(this);
        cadUI.setVisible(true);
    }//GEN-LAST:event_cadastroCompradorActionPerformed

    public void atualizarUsuarioLogado() {
        if (Sistema.getInstance().isLogged()) {
            String nome = Sistema.getInstance().getUsuarioLogado().getNome();
            welcomeLabel.setText("Bem-vindo, " + nome + "!");
        } else {
            welcomeLabel.setText("Não logado");
        }
    }
    
    private void usuarioLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioLoginActionPerformed
        // TODO add your handling code here:
        if (Sistema.getInstance().isLogged()) {
            JOptionPane.showMessageDialog(this, "Usuário já está logado.");
            return;
        }
        LoginUsuarioUI loginUI = new LoginUsuarioUI(this, true);
        loginUI.setLocationRelativeTo(this);
        loginUI.setVisible(true);
        atualizarUsuarioLogado();
    }//GEN-LAST:event_usuarioLoginActionPerformed

    private void anunciosAtivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anunciosAtivosActionPerformed
        // TODO add your handling code here:
        ListarAnunciosAtivos listar = new ListarAnunciosAtivos(this, true);
        listar.setLocationRelativeTo(this);
        listar.setVisible(true);
    }//GEN-LAST:event_anunciosAtivosActionPerformed

    private void anunciosEncerradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anunciosEncerradosActionPerformed
        // TODO add your handling code here:
        ListarAnunciosEncerrados listar = new ListarAnunciosEncerrados(this, true);
        listar.setLocationRelativeTo(this);
        listar.setVisible(true);
    }//GEN-LAST:event_anunciosEncerradosActionPerformed

    private void anunciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anunciosActionPerformed
        // TODO add your handling code here:
        ListarAnuncios listar = new ListarAnuncios(this, true);
        listar.setLocationRelativeTo(this);
        listar.setVisible(true);
    }//GEN-LAST:event_anunciosActionPerformed

    private void buscarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarNomeActionPerformed
        // TODO add your handling code here:
        BuscarAnuncioNome buscar = new BuscarAnuncioNome(this, true);
        buscar.setLocationRelativeTo(this);
        buscar.setVisible(true);
    }//GEN-LAST:event_buscarNomeActionPerformed

    private void anunciosVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anunciosVendedorActionPerformed
        // TODO add your handling code here:
        BuscarAnuncioVendedor buscar = new BuscarAnuncioVendedor(this, true);
        buscar.setLocationRelativeTo(this);
        buscar.setVisible(true);
    }//GEN-LAST:event_anunciosVendedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem anuncios;
    private javax.swing.JMenuItem anunciosAtivos;
    private javax.swing.JMenuItem anunciosEncerrados;
    private javax.swing.JMenu anunciosMenu;
    private javax.swing.JMenuItem anunciosVendedor;
    private javax.swing.JMenuItem buscarNome;
    private javax.swing.JMenuItem cadastroComprador;
    private javax.swing.JMenu cadastroMenu;
    private javax.swing.JMenuItem cadastroVendedor;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu loginMenu;
    private javax.swing.JMenuItem usuarioLogin;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
