/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author vitor
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        cadastroMenu = new javax.swing.JMenu();
        cadastroVendedor = new javax.swing.JMenuItem();
        cadastroComprador = new javax.swing.JMenuItem();
        loginMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cadastroMenu.setText("Cadastro");
        cadastroMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroMenuActionPerformed(evt);
            }
        });

        cadastroVendedor.setText("Cadastro de Vendedor");
        cadastroVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroVendedorActionPerformed(evt);
            }
        });
        cadastroMenu.add(cadastroVendedor);

        cadastroComprador.setText("Cadastro de Comprador");
        cadastroComprador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroCompradorActionPerformed(evt);
            }
        });
        cadastroMenu.add(cadastroComprador);

        jMenuBar1.add(cadastroMenu);

        loginMenu.setText("Login");
        jMenuBar1.add(loginMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroMenuActionPerformed

    }//GEN-LAST:event_cadastroMenuActionPerformed

    private void cadastroVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroVendedorActionPerformed
        // TODO add your handling code here:
        CadastroVendedorUI cadUI = new CadastroVendedorUI(this, true);
        cadUI.setLocationRelativeTo(this);
        cadUI.setVisible(true);
    }//GEN-LAST:event_cadastroVendedorActionPerformed

    private void cadastroCompradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroCompradorActionPerformed
        // TODO add your handling code here:
        CadastroCompradorUI cadUI = new CadastroCompradorUI(this, true);
        cadUI.setLocationRelativeTo(this);
        cadUI.setVisible(true);
    }//GEN-LAST:event_cadastroCompradorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastroComprador;
    private javax.swing.JMenu cadastroMenu;
    private javax.swing.JMenuItem cadastroVendedor;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu loginMenu;
    // End of variables declaration//GEN-END:variables
}
