/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Comprador;
import model.Sistema;
import model.Vendedor;

/**
 *
 * @author vitor
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        cadastroMenu = new javax.swing.JMenu();
        cadastroVendedor = new javax.swing.JMenuItem();
        cadastroComprador = new javax.swing.JMenuItem();
        loginMenu = new javax.swing.JMenu();
        usuarioLogin = new javax.swing.JMenuItem();
        anunciosMenu = new javax.swing.JMenu();
        anuncios = new javax.swing.JMenuItem();
        anunciosAtivos = new javax.swing.JMenuItem();
        anunciosEncerrados = new javax.swing.JMenuItem();
        buscarNome = new javax.swing.JMenuItem();
        anunciosVendedor = new javax.swing.JMenuItem();
        criarAnuncioItem = new javax.swing.JMenuItem();
        contaMenu = new javax.swing.JMenu();
        listarComprasItem = new javax.swing.JMenuItem();
        alterarNomeItem = new javax.swing.JMenuItem();
        alterarEmailItem = new javax.swing.JMenuItem();
        alterarSenhaItem = new javax.swing.JMenuItem();
        logoutItem = new javax.swing.JMenuItem();
        pagamentoMenu = new javax.swing.JMenu();
        adicionarCartaoItem = new javax.swing.JMenuItem();
        removerCartaoItem = new javax.swing.JMenuItem();
        editarCartaoItem = new javax.swing.JMenuItem();
        notificacoesMenu = new javax.swing.JMenu();
        listarNotificacoesItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeLabel.setText("Não Logado");

        cadastroMenu.setText("Cadastro");
        cadastroMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroMenuActionPerformed(evt);
            }
        });

        cadastroVendedor.setText("Cadastro de Vendedor");
        cadastroVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroVendedorActionPerformed(evt);
            }
        });
        cadastroMenu.add(cadastroVendedor);

        cadastroComprador.setText("Cadastro de Comprador");
        cadastroComprador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroCompradorActionPerformed(evt);
            }
        });
        cadastroMenu.add(cadastroComprador);

        jMenuBar1.add(cadastroMenu);

        loginMenu.setText("Login");

        usuarioLogin.setText("Login de Usuário");
        usuarioLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioLoginActionPerformed(evt);
            }
        });
        loginMenu.add(usuarioLogin);

        jMenuBar1.add(loginMenu);

        anunciosMenu.setText("Anúncios");

        anuncios.setText("Todos Anúncios");
        anuncios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anunciosActionPerformed(evt);
            }
        });
        anunciosMenu.add(anuncios);

        anunciosAtivos.setText("Anúncios Ativos");
        anunciosAtivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anunciosAtivosActionPerformed(evt);
            }
        });
        anunciosMenu.add(anunciosAtivos);

        anunciosEncerrados.setText("Anúncios Encerrados");
        anunciosEncerrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anunciosEncerradosActionPerformed(evt);
            }
        });
        anunciosMenu.add(anunciosEncerrados);

        buscarNome.setText("Buscar por Nome");
        buscarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarNomeActionPerformed(evt);
            }
        });
        anunciosMenu.add(buscarNome);

        anunciosVendedor.setText("Buscar por Vendedor");
        anunciosVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anunciosVendedorActionPerformed(evt);
            }
        });
        anunciosMenu.add(anunciosVendedor);

        criarAnuncioItem.setText("Criar Anúncio");
        criarAnuncioItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarAnuncioItemActionPerformed(evt);
            }
        });
        anunciosMenu.add(criarAnuncioItem);

        jMenuBar1.add(anunciosMenu);

        contaMenu.setText("Conta");
        contaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contaMenuActionPerformed(evt);
            }
        });

        listarComprasItem.setText("Listar Compras");
        listarComprasItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarComprasItemActionPerformed(evt);
            }
        });
        contaMenu.add(listarComprasItem);

        alterarNomeItem.setText("Alterar Nome");
        alterarNomeItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarNomeItemActionPerformed(evt);
            }
        });
        contaMenu.add(alterarNomeItem);

        alterarEmailItem.setText("Alterar Email");
        alterarEmailItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarEmailItemActionPerformed(evt);
            }
        });
        contaMenu.add(alterarEmailItem);

        alterarSenhaItem.setText("Alterar Senha");
        alterarSenhaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarSenhaItemActionPerformed(evt);
            }
        });
        contaMenu.add(alterarSenhaItem);

        logoutItem.setText("Logout");
        logoutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutItemActionPerformed(evt);
            }
        });
        contaMenu.add(logoutItem);

        jMenuBar1.add(contaMenu);

        pagamentoMenu.setText("Pagamento");

        adicionarCartaoItem.setText("Adicionar Cartão");
        adicionarCartaoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarCartaoItemActionPerformed(evt);
            }
        });
        pagamentoMenu.add(adicionarCartaoItem);

        removerCartaoItem.setText("Remover Cartão");
        removerCartaoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerCartaoItemActionPerformed(evt);
            }
        });
        pagamentoMenu.add(removerCartaoItem);

        editarCartaoItem.setText("Editar Cartão");
        editarCartaoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarCartaoItemActionPerformed(evt);
            }
        });
        pagamentoMenu.add(editarCartaoItem);

        jMenuBar1.add(pagamentoMenu);

        notificacoesMenu.setText("Notificações");

        listarNotificacoesItem.setText("Listar Notificações");
        listarNotificacoesItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarNotificacoesItemActionPerformed(evt);
            }
        });
        notificacoesMenu.add(listarNotificacoesItem);

        jMenuBar1.add(notificacoesMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroMenuActionPerformed

    }//GEN-LAST:event_cadastroMenuActionPerformed

    private void cadastroVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroVendedorActionPerformed
        // TODO add your handling code here:
        CadastroVendedorUI cadUI = new CadastroVendedorUI(this, true);
        cadUI.setLocationRelativeTo(this);
        cadUI.setVisible(true);
    }//GEN-LAST:event_cadastroVendedorActionPerformed

    private void cadastroCompradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroCompradorActionPerformed
        // TODO add your handling code here:
        CadastroCompradorUI cadUI = new CadastroCompradorUI(this, true);
        cadUI.setLocationRelativeTo(this);
        cadUI.setVisible(true);
    }//GEN-LAST:event_cadastroCompradorActionPerformed

    public void atualizarUsuarioLogado() {
        if (Sistema.getInstance().isLogged()) {
            String nome = Sistema.getInstance().getUsuarioLogado().getNome();
            welcomeLabel.setText("Bem-vindo, " + nome + "!");
        } else {
            welcomeLabel.setText("Não logado");
        }
    }
    
    private void usuarioLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioLoginActionPerformed
        // TODO add your handling code here:
        if (Sistema.getInstance().isLogged()) {
            JOptionPane.showMessageDialog(this, "Usuário já está logado.");
            return;
        }
        LoginUsuarioUI loginUI = new LoginUsuarioUI(this, true);
        loginUI.setLocationRelativeTo(this);
        loginUI.setVisible(true);
        atualizarUsuarioLogado();
    }//GEN-LAST:event_usuarioLoginActionPerformed

    private void anunciosAtivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anunciosAtivosActionPerformed
        // TODO add your handling code here:
        ListarAnunciosAtivos listar = new ListarAnunciosAtivos(this, true);
        listar.setLocationRelativeTo(this);
        listar.setVisible(true);
    }//GEN-LAST:event_anunciosAtivosActionPerformed

    private void anunciosEncerradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anunciosEncerradosActionPerformed
        // TODO add your handling code here:
        ListarAnunciosEncerrados listar = new ListarAnunciosEncerrados(this, true);
        listar.setLocationRelativeTo(this);
        listar.setVisible(true);
    }//GEN-LAST:event_anunciosEncerradosActionPerformed

    private void anunciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anunciosActionPerformed
        // TODO add your handling code here:
        ListarAnuncios listar = new ListarAnuncios(this, true);
        listar.setLocationRelativeTo(this);
        listar.setVisible(true);
    }//GEN-LAST:event_anunciosActionPerformed

    private void buscarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarNomeActionPerformed
        // TODO add your handling code here:
        BuscarAnuncioNome buscar = new BuscarAnuncioNome(this, true);
        buscar.setLocationRelativeTo(this);
        buscar.setVisible(true);
    }//GEN-LAST:event_buscarNomeActionPerformed

    private void anunciosVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anunciosVendedorActionPerformed
        // TODO add your handling code here:
        BuscarAnuncioVendedor buscar = new BuscarAnuncioVendedor(this, true);
        buscar.setLocationRelativeTo(this);
        buscar.setVisible(true);
    }//GEN-LAST:event_anunciosVendedorActionPerformed

    private void alterarNomeItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarNomeItemActionPerformed
        // TODO add your handling code here:
        if (!Sistema.getInstance().isLogged()) {
            JOptionPane.showMessageDialog(this, "Realize login para continuar.");
            return;
        }
        AlterarNome an = new AlterarNome(this, true);
        an.setLocationRelativeTo(this);
        an.setVisible(true);
        atualizarUsuarioLogado();
    }//GEN-LAST:event_alterarNomeItemActionPerformed

    private void alterarEmailItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarEmailItemActionPerformed
        // TODO add your handling code here:
        if (!Sistema.getInstance().isLogged()) {
            JOptionPane.showMessageDialog(this, "Realize login para continuar.");
            return;
        }
        AlterarEmail ae = new AlterarEmail(this, true);
        ae.setLocationRelativeTo(this);
        ae.setVisible(true);
    }//GEN-LAST:event_alterarEmailItemActionPerformed

    private void alterarSenhaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarSenhaItemActionPerformed
        // TODO add your handling code here:
        if (!Sistema.getInstance().isLogged()) {
            JOptionPane.showMessageDialog(this, "Realize login para continuar.");
            return;
        }
        AlterarSenha as = new AlterarSenha(this, true);
        as.setLocationRelativeTo(this);
        as.setVisible(true);
    }//GEN-LAST:event_alterarSenhaItemActionPerformed

    private void logoutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutItemActionPerformed
        // TODO add your handling code here:
        if (!Sistema.getInstance().isLogged()) {
            JOptionPane.showMessageDialog(this, "Realize login para continuar.");
            return;
        }
        Sistema.getInstance().logout();
        atualizarUsuarioLogado();
    }//GEN-LAST:event_logoutItemActionPerformed

    private void contaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contaMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contaMenuActionPerformed

    private void listarComprasItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarComprasItemActionPerformed
        // TODO add your handling code here:
        if (!Sistema.getInstance().isLogged() || Sistema.getInstance().getUsuarioLogado() instanceof Vendedor) {
            JOptionPane.showMessageDialog(this, "Realize login para continuar (como comprador).");
            return;
        }
        ListarCompras lc = new ListarCompras(this, true);
        lc.setLocationRelativeTo(this);
        lc.setVisible(true);
    }//GEN-LAST:event_listarComprasItemActionPerformed

    private void adicionarCartaoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarCartaoItemActionPerformed
        // TODO add your handling code here:
        if (!Sistema.getInstance().isLogged() || Sistema.getInstance().getUsuarioLogado() instanceof Vendedor) {
            JOptionPane.showMessageDialog(this, "Realize login para continuar (como comprador).");
            return;
        }
        AdicionarCartao ac = new AdicionarCartao(this, true);
        ac.setLocationRelativeTo(this);
        ac.setVisible(true);
    }//GEN-LAST:event_adicionarCartaoItemActionPerformed

    private void removerCartaoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerCartaoItemActionPerformed
        // TODO add your handling code here:
        if (!Sistema.getInstance().isLogged() || Sistema.getInstance().getUsuarioLogado() instanceof Vendedor) {
            JOptionPane.showMessageDialog(this, "Realize login para continuar (como comprador).");
            return;
        }
        ListarCartoesRemover lr = new ListarCartoesRemover(this, true);
        lr.setLocationRelativeTo(this);
        lr.setVisible(true);
    }//GEN-LAST:event_removerCartaoItemActionPerformed

    private void editarCartaoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarCartaoItemActionPerformed
        // TODO add your handling code here:
        if (!Sistema.getInstance().isLogged() || Sistema.getInstance().getUsuarioLogado() instanceof Vendedor) {
            JOptionPane.showMessageDialog(this, "Realize login para continuar (como comprador).");
            return;
        }
        ListarCartoesEditar lc = new ListarCartoesEditar(this, true);
        lc.setLocationRelativeTo(this);
        lc.setVisible(true);
    }//GEN-LAST:event_editarCartaoItemActionPerformed

    private void listarNotificacoesItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarNotificacoesItemActionPerformed
        // TODO add your handling code here:
        if (!Sistema.getInstance().isLogged() || Sistema.getInstance().getUsuarioLogado() instanceof Comprador) {
            JOptionPane.showMessageDialog(this, "Realize login para continuar (como vendedor).");
            return;
        }
        MensagensNotificacao mn = new MensagensNotificacao(this, true);
        mn.setLocationRelativeTo(this);
        mn.setVisible(true);
    }//GEN-LAST:event_listarNotificacoesItemActionPerformed

    private void criarAnuncioItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarAnuncioItemActionPerformed
        // TODO add your handling code here:
        if (!Sistema.getInstance().isLogged() || Sistema.getInstance().getUsuarioLogado() instanceof Comprador) {
            JOptionPane.showMessageDialog(this, "Realize login para continuar (como vendedor).");
            return;
        }
        CriarAnuncio ca = new CriarAnuncio(this, true, (Vendedor) Sistema.getInstance().getUsuarioLogado());
        ca.setLocationRelativeTo(this);
        ca.setVisible(true);
    }//GEN-LAST:event_criarAnuncioItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem adicionarCartaoItem;
    private javax.swing.JMenuItem alterarEmailItem;
    private javax.swing.JMenuItem alterarNomeItem;
    private javax.swing.JMenuItem alterarSenhaItem;
    private javax.swing.JMenuItem anuncios;
    private javax.swing.JMenuItem anunciosAtivos;
    private javax.swing.JMenuItem anunciosEncerrados;
    private javax.swing.JMenu anunciosMenu;
    private javax.swing.JMenuItem anunciosVendedor;
    private javax.swing.JMenuItem buscarNome;
    private javax.swing.JMenuItem cadastroComprador;
    private javax.swing.JMenu cadastroMenu;
    private javax.swing.JMenuItem cadastroVendedor;
    private javax.swing.JMenu contaMenu;
    private javax.swing.JMenuItem criarAnuncioItem;
    private javax.swing.JMenuItem editarCartaoItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem listarComprasItem;
    private javax.swing.JMenuItem listarNotificacoesItem;
    private javax.swing.JMenu loginMenu;
    private javax.swing.JMenuItem logoutItem;
    private javax.swing.JMenu notificacoesMenu;
    private javax.swing.JMenu pagamentoMenu;
    private javax.swing.JMenuItem removerCartaoItem;
    private javax.swing.JMenuItem usuarioLogin;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
